name: Test Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  test-build:
    name: Test Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: linux-test
          - os: windows-latest
            artifact_name: windows-test
          - os: macos-latest
            artifact_name: macos-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure npm for Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retries 3
          npm config set fetch-retry-mintimeout 5000
          npm config set fetch-retry-maxtimeout 60000
          npm config set progress false
          npm config set loglevel warn

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: npm ci --no-audit --no-fund --silent --progress=false
        timeout-minutes: 12

      - name: Install dependencies (Unix)
        if: matrix.os != 'windows-latest'
        run: npm ci
        timeout-minutes: 12

      - name: Create Convex API files
        run: |
          mkdir -p convex/_generated
          echo 'export const api = {} as any;' > convex/_generated/api.ts
          echo 'export const internal = {} as any;' > convex/_generated/internal.ts

      - name: Build application
        run: npm run build
        timeout-minutes: 8

      - name: Clean problematic Convex files (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          # Remove problematic Convex files that cause electron-builder issues
          Remove-Item -Path "node_modules/convex/dist/esm-types/test" -Recurse -Force -ErrorAction SilentlyContinue
          Get-ChildItem -Path "node_modules/convex" -Recurse -Filter "*.d.ts.map" | Remove-Item -Force

      - name: Clean problematic Convex files (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          # Remove problematic Convex files that cause electron-builder issues
          rm -rf node_modules/convex/dist/esm-types/test
          find node_modules/convex -name "*.d.ts.map" -delete

      - name: Test Electron build (dir only)
        run: npm run electron:dist -- --dir
        env:
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
        timeout-minutes: 15

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist-electron/
          retention-days: 7 